import type { Metadata } from "next";
import "../sass/main.css"
import { Manrope } from "next/font/google";
import { DataProvider } from "./context/dataContext";
import { CartProvider } from "./context/cartContext";
import Header from "./components/header";
import Footer from "./components/footer"

const manrope = Manrope({
  variable: "--font-Manrope-sans",
  weight: ['400', '600', '700'],
  subsets: ["latin"],
  preload: true,
  display: "swap"
});


export const metadata: Metadata = {
  title: "Frontend Mentor | Audiophile e-commerce website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${manrope.variable}`}>
      <body>
        <CartProvider>
          <DataProvider>
            <Header />
            {children}
            <Footer />
          </DataProvider>
        </CartProvider>
      </body>
    </html>
  );
}
